server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: clientsdb
logging:
  level:
    root: INFO
