spring:
  application:
    name: client-service

  data:
    mongodb:
      uri: mongodb+srv://verdugox123:Aries1990@sortec.rhyde.mongodb.net/clientsdb?ssl=true&retryWrites=true&w=majority

#  ssl:
#    enabled: true

server:
  port: 8086

logging:
  level:
    root: INFO              # Nivel de log global
    org.mongodb.driver: DEBUG # Detalles de MongoDB (conexiones, consultas)
    org.springframework.web: DEBUG # Peticiones HTTP entrantes y salientes
    org.springframework.data: DEBUG # Interacciones con repositorios de datos
    org.springframework.boot: INFO # Logs de inicialización de Spring Boot
    reactor: DEBUG           # Logs del flujo reactivo

