spring:
  application:
    name: client-service

  data:
    mongodb:
      uri: mongodb+srv://verdugox123:Aries1990@sortec.rhyde.mongodb.net/clientsdb&appName=Sortec

  ssl:
    enabled: true

server:
  port: 8086
  ssl:
    trust-store: classpath:truststore.jks
    trust-store-password: Aries1990$ # Cambiar por la contraseña real usada en el truststore

logging:
  level:
    root: INFO
    org.mongodb.driver: DEBUG
