spring:
  application:
    name: client-service

  data:
    mongodb:
      uri: mongodb+srv://verdugox123:Aries1990@sortec.rhyde.mongodb.net/clientsdb?retryWrites=true&w=majority&ssl=true
  ssl:
    enabled: true

server:
  port: 8086  # Cambié el puerto a 8086 para alinearlo con tu configuración actual

logging:
  level:
    root: INFO  # Nivel de log global
    org.mongodb.driver: DEBUG  # Logs detallados para MongoDB
