pipeline {
    agent any

    environment {
        MONGO_URI = 'mongodb://localhost:27017/clientsdb'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/verdugox/client-service.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'java -jar target/client-service-0.0.1-SNAPSHOT.jar'
            }
        }
    }
}
